image: gradle:6.1.1-jdk8

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

stages:
  - test


test:t1:
  stage: test
  script: gradle :MyAc:check
