image: gradle:6.1.1-jdk8

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - echo "Mudah mudahan lancar"
  - echo `pwd`
  - export GRADLE_USER_HOME=`pwd`/.gradle
  - rm -f  .gradle/caches/modules-2/modules-2.lock
  - rm -fr .gradle/caches/*/plugin-resolution/

stages:
  - build
  - test
  - deploy

Build:
  stage: build
  script:
    - gradle build

Test:
  stage: test
  script:
    - gradle :MyAc:check
    - gradle :MyAc:jacocoTestReport
    - cat MyAc/build/reports/jacoco/test/html/index.html

test:ali:
  stage: test
  script:
    - gradle :ali:check
    - gradle :ali:jacocoTestReport
    - cat MyAc/build/reports/jacoco/test/html/index.html

test:forum:
  stage: test
  script:
    - gradle :forum:check
    - gradle :forum:jacocoTestReport
    - cat MyAc/build/reports/jacoco/test/html/index.html

test:InformasiDetailPerMatkul:
  stage: test
  script:
    - gradle :InformasiDetailPerMatkul:check
    - gradle :InformasiDetailPerMatkul:jacocoTestReport
    - cat MyAc/build/reports/jacoco/test/html/index.html

test:Alvin:
  stage: test
  script:
    - gradle :Alvin:check
    - gradle :Alvin:jacocoTestReport
    - cat MyAc/build/reports/jacoco/test/html/index.html

test:login:
  stage: test
  script:
    - gradle :login:check
    - gradle :login:jacocoTestReport
    - cat MyAc/build/reports/jacoco/test/html/index.html

Production:
  image: ruby:2.4
  stage: deploy
  before_script:
    - gem install dpl
    - wget -qO- https://cli-assets.heroku.com/install-ubuntu.sh | sh
  script:
    - dpl --provider=heroku --app=$HEROKU_APPNAME --api-key=$HEROKU_APIKEY
    - export HEROKU_API_KEY=$HEROKU_APIKEY
    - heroku run --app $HEROKU_APPNAME migrate
  environment:
    name: production
    url: $HEROKU_APP_HOST


after_script:
  - echo "Mantab jiwa"
