image: gradle:6.1.1-jdk8

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

stages:
  - test

<<<<<<< HEAD

test:t1:
  stage: test
  script:
    - gradle :MyAc:check
    - gradle :MyAc:jacocoTestReport
=======
# Tutorial 1 CI Jobs
test:t1:
  stage: test
  script: gradle :MyAc:check
>>>>>>> d40e66f898f71c17d43a67dabd4c3b7f7dbcea1d
