INSERT INTO matkul (kode, nama, semester, sks) VALUES ('CS00000', 'DDP1', 1, 4);
INSERT INTO matkul (kode, nama, semester, sks) VALUES ('CS00001', 'MatDis 1', 1, 3);
INSERT INTO long_plan (id, kode_user, nama) VALUES (1, 1806141132, 'To Be Great Web Developer');
INSERT INTO long_plan (id, kode_user, nama) VALUES (2, 1806141133, 'Hacker');
INSERT INTO long_plan (id, kode_user, nama) VALUES (3, 1806141134, 'System Administrator');
INSERT INTO long_plan (id, kode_user, nama) VALUES (4, 1806141135, 'AI Master');
INSERT INTO long_plan (id, kode_user, nama) VALUES (5, 1806141136, 'To Be Mobile App Developer');
INSERT INTO semester_plan (id, semester) VALUES (1, 1);
INSERT INTO semester_plan (id, semester) VALUES (2, 2);
INSERT INTO semester_plan (id, semester) VALUES (3, 3);
INSERT INTO semester_plan (id, semester) VALUES (4, 4);
INSERT INTO semester_plan (id, semester) VALUES (5, 5);
